import { z } from 'zod';

const table = z.record(z.string(), z.string());

/** resources/icons/mapping.json (DATA-FORMATS.md §6). */
export const IconTables = z.object({
  creatureType: table.default({}),
  ancestry: table.default({}),
  nameKeywords: table.default({}),
  synonyms: table.default({}),
  itemType: table.default({}),
  spellSchool: table.default({}),
});
export type IconTables = z.infer<typeof IconTables>;

/** resources/icons/credits.json, generated by scripts/fetch-game-icons.ts. */
export const IconCredits = z.object({
  license: z.object({ name: z.string(), url: z.string() }),
  source: z.string(),
  authors: z.array(z.object({ name: z.string(), icons: z.number().int().min(0) })),
});
export type IconCredits = z.infer<typeof IconCredits>;
